### ISSUE TITLE
stack private packages

### ISSUE THREAD

**Issue by Pitometsu** [aloiscochard/codex#72]
E.g. I hase `stacke.yaml` with some dependencies in private github repos like that:

```yaml
resolver: lts-9.3

packages:
- '.'
- location:
git: https://my-reponame:github-secure-hash@github.com/my-reponame/my-reponame.git
commit: some-commit-hash
extra-dep: true
subdirs:
- src-subdir-name
```
Than I got `404` errors from `codex`
```
$ codex update
( . . . )
(StatusCodeException (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx/1.10.3 (Ubuntu)"),("Content-Type","text/plain"),("Via","1.1 varnish"),("Fastly-Debug-Digest","some-hash"),("Content-Length","51"),("Accept-Ranges","bytes"),("Date","Mon, 18 Sep 2017 10:51:12 GMT"),("Via","1.1 varnish"),("Age","0"),("Connection","keep-alive"),("X-Served-By","cache-dfw1838-DFW, cache-hhn1535-HHN"),("X-Cache","MISS, MISS"),("X-Cache-Hits","0, 0"),("X-Timer","S1505731872.961809,VS0,VE509"),("Vary","Accept-Encoding")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "Package not found: No such package version for my-reponame\n")
( . . . )

**Comment by JakeAndrew** [comment]
Superficially, this appears to be a duplicate of #48. 

Looking deeper, your grouping/indentation doesn't seem right.

Does the below work for you?

```yaml
resolver: lts-9.3

packages:
  - '.'
  - location:
      git: https://my-reponame:github-secure-hash@github.com/my-reponame/my-reponame.git
      commit: some-commit-hash
      subdirs:
        - src-subdir-name
    extra-dep: true
```

I give a link to a script in #48's discussion that should help you.
